### ISSUE TITLE
prcGetAllRoutesForMap doesn't display the latest session location

### ISSUE THREAD

**Issue by htrendev** [nickfox/GpsTracker#14]
It seems that the location displayed on the map is the first session location and not the latest one. The following change of the prcGetAllRoutesForMap procedure fixed the problem for me:
```sql
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `prcGetAllRoutesForMap`()
BEGIN
  SELECT gps1.sessionId, gps1.gpsTime,
  CONCAT('{ "latitude":"', CAST(gps1.latitude AS CHAR),'", "longitude":"', CAST(gps1.longitude AS CHAR), '", "speed":"', CAST(gps1.speed AS CHAR), '", "direction":"', CAST(gps1.direction AS CHAR), '", "distance":"', CAST(gps1.distance AS CHAR), '", "locationMethod":"', gps1.locationMethod, '", "gpsTime":"', DATE_FORMAT(gps1.gpsTime, '%b %e %Y %h:%i%p'), '", "userName":"', gps1.userName, '", "phoneNumber":"', gps1.phoneNumber, '", "sessionID":"', CAST(gps1.sessionID AS CHAR), '", "accuracy":"', CAST(gps1.accuracy AS CHAR), '", "extraInfo":"', gps1.extraInfo, '" }') json
  FROM gpslocations gps1
  LEFT JOIN gpslocations gps2 ON (gps1.sessionId = gps2.sessionId AND gps1.GPSLocationID < gps2.GPSLocationID)
  WHERE gps1.sessionID != '0' && CHAR_LENGTH(gps1.sessionID) != 0 && gps1.gpstime != '0000-00-00 00:00:00' && gps2.GPSLocationID is NULL
  ORDER BY gpsTime ASC;
END ;;
DELIMITER ;
```
all credits go to http://stackoverflow.com/questions/1313120/retrieving-the-last-record-in-each-group

**Comment by MrFurther** [comment]
I'm still facing this issue (I'm running the last version).
On the first map, where it displays all the possible routes, the marker will be placed where the first record was made, not where the last one was (present location).

Any tips?

**Comment by nickfox** [comment]
Hi

I think there is a regression error in the latest code. Did you try the stored procedure above from Hristo?

Nick

**Comment by MrFurther** [comment]
Hi Nick!
Just tried it, worked like a charm! : )
Thanks!

Eric

**Comment by nickfox** [comment]
Excellent, I will update gps tracker with that fix in the next couple of days. Good luck with it, Eric.

n

**Comment by MrFurther** [comment]
Thanks Nick!
I have a doubt unrelated to this issue, where could I inquire about it? Is not an issue per se(therefore not to be opened here), more a logical/procedural doubt..

**Comment by nickfox** [comment]
best to ask questions on websmithing.com so others can see it too.
