### ISSUE TITLE
Caching problem? (Not all locations shown on map)

### ISSUE THREAD

**Issue by meinme** [nickfox/GpsTracker#26]
First of all: Thanks for your effort! 
While searching the web for a tracking app, this is the only app working according to the "Need to know" principle: Any other app requires access to the phone's contacts and even my private images and SD card. Yours does what people would expect: Is sends GPS coordinated to a DB and presents them on a map. Simple and sufficient! Thank you!
I tested the app with https://www.websmithing.com/gpstracker/displaymap.php and wondered why I cannot find myself. I turned the app on and off, reinstalled, changed the user name and all of a sudden I appeared with the first user name I chose. After a couple of minutes later and after pressing F5 several times my other user names showed up as well.
I installed the PHP-version of your app on my local server and turned off caching by using the following META-tags without success:
	<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
	<META HTTP-EQUIV="Expires" CONTENT="-1">
In my local DB, I can see the tracking items coming in as they should. Despite of that, the displaymap.php keeps showing incomplete results. F5 is a relieve here but not a solution. 
Your app seems to be very mature which is why I doubt that the “error” I experience is a general one based in your code.
Nevertheless, I wanted to raise this point.
Have you ever heard of any such issue?

**Comment by brentfraser** [comment]
You could try clicking the "Auto Refresh Off" button to switch it to "Auto refresh On"
