### ISSUE TITLE
how to obtain user gps location information when visiting the web page?

### ISSUE THREAD

**Issue by buddhists** [nickfox/GpsTracker#27]
I noticed android browser can get my GPS location information, so I hope it can add a point in display map.php, So it can show the visitor's current gps location and  compare the history locations. 
there is a web page tell how to get GPS location:
https://developers.google.com/web/fundamentals/device-access/user-location/obtain-location?hl=en
So could you tell me how to add this point into the web code?

**Comment by buddhists** [comment]
I also suggest to add a Date select link to filter those route by date first, when recording these routes every day, then this select link would be too long.

**Comment by brentfraser** [comment]
good idea.  And we need to make a mobile-friendly web mapping page.
