### ISSUE TITLE
dotNET server with MySql DB : json parsing error

### ISSUE THREAD

**Issue by mahermeg17** [nickfox/GpsTracker#32]
Hi,
I'm using the dotNet server version with mysql database. I modified the necessary and the project is running well with visual studio 2013. But there is a json parsing error when showing the map

    maps.js:62 error status: parsererror
    maps.js:63 errorThrown: SyntaxError: Unexpected token B
    maps.js:64 Object {readyState: 4, responseText: "{ "locations": [8BA21D90-3F90-407F-BAAE-800B04B1F5…B04B1F5EC,8BA21D90-3F90-407F-BAAE-800B04B1F5ED] }", status: 200, statusText: "OK"}abort: (a)arguments: nullcaller: nulllength: 1name: ""prototype: m.extend.ajax.v.abortconstructor: (a)__proto__: Object__proto__: ()<function scope>always: ()complete: ()done: ()error: ()fail: ()getAllResponseHeaders: ()getResponseHeader: (a)overrideMimeType: (a)pipe: ()progress: ()promise: (a)readyState: 4responseText: "{ "locations": [8BA21D90-3F90-407F-BAAE-800B04B1F5EB,8BA21D90-3F90-407F-BAAE-800B04B1F5EC,8BA21D90-3F90-407F-BAAE-800B04B1F5ED] }"setRequestHeader: (a,b)state: ()status: 200statusCode: (a)statusText: "OK"success: ()then: ()__proto__: Object

**Comment by mahermeg17** [comment]
Hi,
I want to add that when using a debug string into the DbJsonReader, the call for "locations", it means call for the prcGetAllRoutesForMap the json has a wrong format. not like "routes"

     { "locations": [8BA21D90-3F90-407F-BAAE-800B04B1F5EB,8BA21D90-3F90-407F-BAAE-800B04B1F5EC,8BA21D90-3F90-407F-BAAE-800B04B1F5ED] }

     { "routes": [{ "sessionID": "8BA21D90-3F90-407F-BAAE-800B04B1F5ED", "userName": "gpsTracker1", "times": "(Jan 3 2007 08:43PM - Jan 3 2007 08:45PM)" },{ "sessionID": "8BA21D90-3F90-407F-BAAE-800B04B1F5EC", "userName": "gpsTracker2", "times": "(Jan 3 2007 08:40PM - Jan 3 2007 08:42PM)" },{ "sessionID": "8BA21D90-3F90-407F-BAAE-800B04B1F5EB", "userName": "gpsTracker3", "times": "(Jan 3 2007 08:37PM - Jan 3 2007 08:39PM)" }] }

**Comment by nickfox** [comment]
I'm not 100% sure that the the dotNet version and the php version are compatible. Why are you mixing up the two?

n

**Comment by mahermeg17** [comment]
I need to integrate the gps tracker into as a module into an other project.
But it's ok now. I fixed it by changing the select query into the prcGetAllRoutesForMap like this :

     ....
     SELECT CONCAT('{ "latitude":"', CAST(latitude AS CHAR),'", "longitude":"', 
     CAST(longitude AS CHAR), '", "speed":"', CAST(speed AS CHAR), '", "direction":"', 
     CAST(direction AS CHAR), '", "distance":"', CAST(distance AS CHAR), '", "locationMethod":"',
      locationMethod, '", "gpsTime":"', DATE_FORMAT(gpsTime, '%b %e %Y %h:%i%p'), '", 
     "userName":"', userName, '", "phoneNumber":"', phoneNumber, '", "sessionID":"', 
     CAST(sessionID AS CHAR), '", "accuracy":"', CAST(accuracy AS CHAR), '", 
     "extraInfo":"', extraInfo, '" }') json
     FROM ...

**Comment by nickfox** [comment]
cool, very good.

n
