### ISSUE TITLE
No display map

### ISSUE THREAD

**Issue by terradigital** [nickfox/GpsTracker#38]
Hi!

I installed PHP and Wordpress version.
No work!
No errors!
I'm confused.
See:
http://www.rotaryclubdabahia.com.br/teste/displaymap.php

Thanks for helping 
Kind Regards

**Comment by Bigood** [comment]
You have two server errors (noticed by checking the js console on your page).

On http://www.rotaryclubdabahia.com.br/teste/getallroutesformap.php :
> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: v_GetAllRoutesForMap' in /home/storage/d/ae/19/rotaryclubdabahia3/public_html/teste/getallroutesformap.php:11 Stack trace: #0 /home/storage/d/ae/19/rotaryclubdabahia3/public_html/teste/getallroutesformap.php(11): PDO-prepare('select * from v...') #1 {main} thrown in /home/storage/d/ae/19/rotaryclubdabahia3/public_html/teste/getallroutesformap.php on line 11

On http://www.rotaryclubdabahia.com.br/teste/getroutes.php

> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: v_GetRoutes' in /home/storage/d/ae/19/rotaryclubdabahia3/public_html/teste/getroutes.php:10 Stack trace: #0 /home/storage/d/ae/19/rotaryclubdabahia3/public_html/teste/getroutes.php(10): PDO->prepare('select * from v...') #1 {main} thrown in /home/storage/d/ae/19/rotaryclubdabahia3/public_html/teste/getroutes.php on line 10

Did you generate your database ?

**Comment by terradigital** [comment]
Grateful for the warning!
Installed in Wordpress!
