### ISSUE TITLE
Not display all users , and different colors

### ISSUE THREAD

**Issue by zera272** [nickfox/GpsTracker#39]
Hello, i cloned to this repo and run it locally, but i got something strange here,
i add more datas to gpslocation table, when i reload my displaymap.php
they didn't show up, only show when i track it from select option below of the map,
and why they have different color ?
please answer , thank you

**Comment by brentfraser** [comment]
The data is organized into "sessions".  Different sessions could be different phones, or they could be the same phone at different times (if the user has turned off tracking then turned it on again).  Each session in the database is listed in the "Select Route" drop down list.  You can select a session for display if you want to display only one,   The latest position in the session is colored red, all the other positions in the session are blue-green.

**Comment by bavillaloboso** [comment]
It may be the procedure , prcGetRoutes which may have problems with the collation of your database review

**Comment by zera272** [comment]
Thank you , done :+1:
