### ISSUE TITLE
Question: Date given in local time; how to get UTC?

### ISSUE THREAD

**Issue by cjrh** [nickfox/GpsTracker#40]
Apologies if this is explained somewhere; I've looked around and can't find it.  

In the Android _Gps Tracker_ app, the messages look like this:

```
GET /?longitude=153.1261661&latitude=-27.6183941&extrainfo=0&username=abc&distance=0.0&date=2016-04-06%2B13%253A29%253A43&direction=0&accuracy=119&phonenumber=46a0893b-15c7-44e9-90c8-d57af541f4d3&eventtype=android&sessionid=ba82d977-9f64-4179-96db-9950bedfcda7&speed=0&locationmethod=fused HTTP/1.1\r\nHost: rdev.gpsbe.net:5019\r\nConnection: Keep-Alive\r\nAccept-Encoding: gzip\r\n\r\n
```

In particular, the `date` field appears to be local time.  Is there some obvious way to get that reported in UTC, or will I have to detect local timezone from GPS coordinates and convert back to UTC myself?

**Comment by nickfox** [comment]
You'll need to look at using the proper formatter. Check out these on stackoverflow.

http://stackoverflow.com/questions/2818086/android-get-current-utc-time

http://stackoverflow.com/questions/308683/how-can-i-get-the-current-date-and-time-in-utc-or-gmt-in-java

n

**Comment by cjrh** [comment]
Ok thank you.
