### ISSUE TITLE
Google limitation

### ISSUE THREAD

**Issue by zera272** [nickfox/GpsTracker#41]
Hello guys, i have many users to be displayed on a map,
and i make it reloaded (map) on every 10seconds ,
and i see it uses google map, so my question is will google limit it ?
is there limitation to use this map ?
for example the limit is 1M requests (reload map) everyday .
thank you

**Comment by brentfraser** [comment]
You would have to look at the Google documentation to find any Google Maps limit.   you could use OpenStreetMap tiles if Google is too limiting.  Click on the layers icon on the top right of the map on your GpsTracker page to switch to OpenStreetMap.
