### ISSUE TITLE
GPS.getLocation: java.lang.NullPointerException

### ISSUE THREAD

**Issue by esteves67** [nickfox/GpsTracker#42]
First of all, thanks for this wonderful code given to us for free,

So i got everything to work in localhost, php server side + sql + android client version, displaying map correctly and storing data in database, but i got like 10 blackberry phones (9620 model), android phones are expensive here were i live =( and i cant get javaME client version to work =( sorry for posting this question but im trying like 4 ~ 5 days, tried everything =/

In the real phone i get that error below:
GPS.getLocation:
java.lang.NullPointerException

In the emulator i get: ( i think it is because its a emulator and it doesnt have internet connection )
NetWorker.postGpsData error:
java.io.IOException: Alert (2,40)type:22

Im using Netbeans IDE 7.4, gps tracker 5.1.1.
Can someone that use javaME version help me pls?

Thank you guys very much
ps: sorry for my bad english im from brazil xD

**Comment by brentfraser** [comment]
This looks like a generic http connection error, not related specifically to the GPSTracker code.  Some Googling suggests it might be related to your server's certificate or an SSL version.  Or possibly an API permission problem (I'm not a phone developer).

**Comment by esteves67** [comment]
that was what i was thinking, because one time i got a APN error too, and gps tracker doesnt have
javax.microedition.io.httpconnection in his mid profile, i was looking into the dead instamapper blackberry app jad (that use gps tracker source) and it have that mid profile and others.

thank you so much Mr. Brent
now im in the right path to know how to fix this
im not a java developer, so your tip helped me thanks :D
