### ISSUE TITLE
TK130b only

### ISSUE THREAD

**Issue by jccalbuquerque** [nickfox/GpsTracker#43]
I need only record the data sent by crawlers in my database using PHP MySql with TK103b protocol.
I can do this using the example of TK103-server.php?
How to make so that the server is always "listening" and recording the data? Through CRON?

If someone help, thank you.

**Comment by brentfraser** [comment]
Yes you can use the TK103-server.php as an example on how to implement TK103b protocol.  The differences could be small (but some of the handshaking differences could be large).

As for monitoring the server, you could build a client app (or script) to do an insert, a query and then a delete.  Server monitoring is a big topic and it depends on what you want to do,so you may need to do some Googling.
