### ISSUE TITLE
not hitting updatelocation.php

### ISSUE THREAD

**Issue by sydeburnz** [nickfox/GpsTracker#46]
looking at my logs, it seems my phone randomly stops sending data.  i have checked my webserver logs and for instance, today it stopped sending data about 2 hours ago, but the app is still running on my phone.  also, my friend who is helping me test, it never seems to send any data.  he has not showed up in the databases at all  using php, non wordpress version of app.

**Comment by sydeburnz** [comment]
maybe an issue with the android app?  it seems if i restart my app, it started tracking again, not sure for how long though.  will report back.

**Comment by sydeburnz** [comment]
sorry, spoke too soon, i guess the marker on the map is still from 2 hours ago :(

**Comment by brentfraser** [comment]
On your GpsTracker page, you can press the button "Auto Refresh Off" to change to "Auto Refresh On".  It will then center the map on route every minute.
