### ISSUE TITLE
Blackberry 10

### ISSUE THREAD

**Issue by Weetrucker** [nickfox/GpsTracker#61]
Is there a way to merge this github
https://github.com/blackberry/BES10-WebWorks/tree/master/Headless-GPS-Surveillance
with yours to add BB10 phone clients

**Comment by brentfraser** [comment]
Maybe Nick could offer his opinion, but from my perspective:

1. Merge the two code/projects in github?  
           No, it's ok (and maybe a good thing) for the projects to stay separate.

2. Add the ability in GpsTracker server code to accept BB10 locations?  
           Sure! Add a PHP function (say updatelocationBB10.php) to translate the BB10 url parameters for insertion into the database.  Maybe construct a sessionID = pin+day or something similar.

**Comment by Weetrucker** [comment]
Sorry if said it wrong I am not a githuber I just like this app and would like to deploy it for a event that I hold every year

**Comment by brentfraser** [comment]
That's ok.  I figured you were just wondering if they could be used together (and the answer is Yes!, with a little server-side PHP programming...

**Comment by nickfox** [comment]
I haven't looked at the BB code but I would say yes. In order for that to happen, we would need to acquire a BB10 from you (that we would keep). We would need that for testing. I had considered supporting BB in the past but when android and iphone came out, BB just died and there was no call for it...

**Comment by Weetrucker** [comment]
whoa horse trading I love it I have a Z10 you can have I will just have to get it unlock for your provider  
contact me at jacksebay at gmail dot com and we can chat about my project
Al

**Comment by nickfox** [comment]
Oh no, this isn't horse trading. I have no desire to own a BB and probably would give it away to a friend. I just simply don't want to have to repackage it and go to the post office and mail it back. And also, the 50 or 75 dollars that the phone may cost is far from what we charge clients for this kind of work.

I had a chance to look at the BB code (written in c++). It looks pretty straightforward and can probably be modified to work with gps tracker. If your BB has to be unlocked to work on my network, that also is a problem. I live in France and that's going to be hard to unlock it to work here (I suspect). It's just these little things that start to add up in time. Maybe Brent has some interest in doing it. My interest level is pretty low, it really doesn't add a lot to gps tracker. 

To be honest, I didn't even realize blackberry was still in business...

**Comment by Weetrucker** [comment]
Ok no bb10

I only have on question and I will move on

how do you delete the user's data automatically when they turn the tracker off (clear the map)?

**Comment by nickfox** [comment]
The easiest way is to use the "extrainfo" field from the phone and pass an "x" back to the server in that field. On the php page, you have an if block, if the field equals x, then call a procedure in the DB that deletes all the rows associated with that sessionID, if not the just add that row to the DB.

When a person taps on stop tracking on the phone, that's when you send the row with the x. That will do it.
