### ISSUE TITLE
Design of Website Crash, if i activate the Plugin

### ISSUE THREAD

**Issue by corincorvus** [nickfox/GpsTracker#65]
Hello,

i want to track my Position on my Website and i installed your Plugin. After i activated your Plugin, my Website doesnt look correctly. (Look @ the Attached Files)

I think, its not compatible with my Wordpress Version (4.6).

May you update your Plugin or help me to solve the Problem?

Best regards

![correct](https://cloud.githubusercontent.com/assets/21257329/17997770/d91255a0-6b70-11e6-813f-77b79245c46a.PNG)
![incorrect](https://cloud.githubusercontent.com/assets/21257329/17997769/d9114cc8-6b70-11e6-89f7-07c3497bea44.PNG)

**Comment by nickfox** [comment]
Can you please turn off your other extensions and see if it works properly. If not, give me the url of your display map.

n

**Comment by corincorvus** [comment]
I can't turn off all other Extensions, because the Site is online and in use. 
May you give me specificly extensions, who block or disturb your Extension?

My URL ist: http://corvuscorporation.de/
At the Moment the Extension isn't enabled

**Comment by nickfox** [comment]
There are thousands of extensions. I have no idea at all.

**Comment by corincorvus** [comment]
I test it tonight. On 1 o Clock nobody use the Site. Tomorrow i post it.

**Comment by nickfox** [comment]
ok, ping me when you get it back up again and have the other plugins turned off and if I'm at my computer, I'll have a look at it. In chrome browser, you can check the javascript editor and see what the error is.

**Comment by corincorvus** [comment]
Now all disabled and GPS Tracker is Enabled. The Site is incorrect.

**Comment by corincorvus** [comment]
Now i needed to enable other plugins, because a bot create accounts on my website... -.-

**Comment by nickfox** [comment]
Here is the error I am seeing.

js?sensor=false&ver=4.6:93 You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

**Comment by corincorvus** [comment]
Hm okay. I dont have any other map Plugin installed. How it can be?
