### ISSUE TITLE
.

### ISSUE THREAD

**Issue by esteves67** [nickfox/GpsTracker#71]
.

**Comment by mygpstracker** [comment]
Yes use leaflet awesome markers

**Comment by esteves67** [comment]
@mygpstracker Thank you Sir, awesome webapp created by you (mygpstracker xyz), im already "subscribed" xD, you did some very cool implementations, is it free to use / modify?

Thank you for the help to number icons, already found some things about it on stackoverflow

**Comment by extremeweather1** [comment]
yes sir!

Respectfully,

......................................

*OTC Exchange, Inc.*
*John D. Jarvis*
FM 3083 Teas Rd @ Plantation Dr , Suite 100, Conroe, TX 77303
Office: *(214) 799-0542*
EMail: OTCExchange@gmail.com
www: http://www.otcexchange.company
Office Location: Map
<https://www.google.com/maps/place/OTC+Exchange,+Inc./@30.343336,-95.476277,17z/data=!3m1!4b1!4m2!3m1!1s0x86473ea03c29aa07:0x11abb3bea85f2eae>

*PRIVATE, PERSONAL & CONFIDENTIAL DISCLAIMER: This communication is not to
be considered a solicitation for any purpose in any form or content, nor is
it an offer to sell and/or buy securities. This communication contains
privileged and confidential information covered by the US Electronic
Communications Privacy Act, 18 U.S.C. §§ 2510-2521, intended solely for the
use of the addressee(s). The text and amendments, where applicable, are
also protected from disclosure by and under the US Gramm-Leach-Bliley Act.
Upon receipt of this you hereby agree and accept this to be unsolicited,
privileged, proprietary and confidential for your interest only and to be
kept private. If this was addressed to you in error, please, immediately
alert the sender by reply e-mail and delete its entirety, as any use,
distribution, copying, or storage of this communication is strictly
prohibited and prosecutable. *

*Sender is not a United States Securities Dealer nor a Securities Broker
nor US Investment Adviser nor a Commercial Banking Institution or Insurance
Company. Sender is not licensed to buy or sell securities and anything in
this email should not be construed as an offer to buy or sell any
securities or interpreted as advice of any kind for the purchase or sale of
securities.*
