### ISSUE TITLE
Google Map not Working on Php

### ISSUE THREAD

**Issue by pharidali** [nickfox/GpsTracker#76]
Please check

 http://jaanirakhe.com/kyrol/displaymap.php 

Google map not working but OpenStreetMaps Working.

**Comment by nickfox** [comment]
You need to install the google maps key.

n

**Comment by pharidali** [comment]
where brother?

**Comment by nickfox** [comment]
https://www.google.fr/search?q=google+maps+key&oq=google+maps+key&aqs=chrome..69i57j0l5.214j0j4&sourceid=chrome&ie=UTF-8

**Comment by pharidali** [comment]
i got key. now where to put the key brother?

**Comment by pharidali** [comment]
..

**Comment by nickfox** [comment]
it's in maps.js. You'll need to figure it out. It is a new thing from google. I have not done it yet. The link I provided should explain.

n

**Comment by pharidali** [comment]
thank you.
