### ISSUE TITLE
PHP Socket Server not working

### ISSUE THREAD

**Issue by deccosantos** [nickfox/GpsTracker#82]
Hi, i'm trying to use this code to test into my tk303 tracker. But my problem is that my tracker can't connect to the socket server.

I'm setting into the server page the ip 127.0.0.1 on port 8080.
The port ia already opened, I know this because i can access the url outside my home connection, but my tracker is not connecting.

When I set my tracker to adminip of http://www.gpstrackerxy.com works greatly, but to my network ip is not working, can someone help me in what i'm doing wrong?

**Comment by nickfox** [comment]
That is not an easy piece of software to work with. I suspect that part of the problem is that you are using a different model than the one we tested with. That means you need to figure out what all the calls are to the server. It's a bit of guesswork and a lot of googling to get there. It took me a couple of days just for that one model we used.

**Comment by deccosantos** [comment]
But i talked with the coban support and they sent me the protocol of the tk303g and the initial message is ##,imei:xxxxxxxxxxxxx... this is equal tk103.

Is there a way to test the socket server to ser how many connectiona are online in windows?

Let me know, in the server i must ser 127.0.0.1 as ip or i need to set my network ip?

**Comment by nickfox** [comment]
are you putting lots of "echo"s in the code to see what is happening on the server?

**Comment by deccosantos** [comment]
no, i just set 2 echos and that's the same message that i'm passing to socket_write and socket_send.

I'm thinking that the tracker is not connecting because it's not reveiving the LOAD and ON msg from server.

I'm using socket_write to send LOAD if the $buf starts with ##, and ON if receives my tracker imei, but nothing happens.

I should do anything else to work?

**Comment by nickfox** [comment]
Most importantly, did you test it first with the client I wrote?

**Comment by deccosantos** [comment]
Yes, but i just got ON as answer, never got LOAD

**Comment by nickfox** [comment]
You need to just focus on those 2 pieces of software. Write lots of echo statements.

**Comment by deccosantos** [comment]
I found my problem. However my port 8080 was open, my socket server is not allowing connectiona from outside my local network, how can I solve this?

**Comment by nickfox** [comment]
What was the problem?

**Comment by deccosantos** [comment]
I don't know why my socket server is not allowing connections outside my local web, thus i can't set up the tracker to connect to my ip

**Comment by nickfox** [comment]
you need to figure out what ip is addressed to your local computer and use that. Isn't it ipconfig?

**Comment by deccosantos** [comment]
I have already set my machine to 192.168.254.15 and the port 8080 is directing to this. But when i configure my socket server i don't know if I need to set with the ip 127.0.0.1, if i need to set 192.168.254.15 or if I need to set my network ip 187.59.251.XXX and start the server.php, what ip should i use?

**Comment by nickfox** [comment]
try ALL of the different combinations.

**Comment by nickfox** [comment]
experiment until you find it.

**Comment by nickfox** [comment]
And the php socket server must be running.

**Comment by deccosantos** [comment]
I know this. As i said, the server in local network is working normally, when i run the php file in wamp and connect via telnet in cmd. But when I try to connect from my 3g connection in my phone I always get connected but server net sends the message I wrote to send, and server never gets the message i sent from phone, and I realize that is because the server is creating a false connection that do not catch any info from device and do not send either

**Comment by deccosantos** [comment]
I solve the problem! My problem is that when i set the 127.0.0.1 as ip and run the server, it only works in local connection. I needed to set my ip to 192.168.254.15, thats my machine ip and so server works greatly, now everything is working... thanks for you great work!

👏👏

**Comment by nickfox** [comment]
Excellent, glad to see you figured it out.
