### ISSUE TITLE
Tracker not reading response

### ISSUE THREAD

**Issue by deccosantos** [nickfox/GpsTracker#86]
Hi Nick, please help me i'm wanting to send codes to my tracker but it's not reading or i'm doing something wrong because i'm trying to send, for example this cose **,imei:<myimei>,509; (509 is the code to power off when car is lower then 20km/h, but nothing happens. I saw in your server code that when server get help me the response is **,imei:<imei>,E; I'm wanting to know what means this "E" bacause I can't find in gprs protocol nothing about letters in codes, where can I find letters as codes to send to tracker?
Since now, thanks for all

**Comment by brentfraser** [comment]
These protocols are very device specific.  You need to use the codes for your device.

**Comment by deccosantos** [comment]
I know that, I´m using a Coban tk303g, and I asked for gprs protocol to a coban salesman and he says that tk303 is the same protocol of tk103 but when i send codes to tracker with numeric keyword nothing happens.

**Comment by brentfraser** [comment]
I think the device nick and I were testing was a GPS306A so the protocol was slightly different than a TK103.  If you look at "coban GPRS protocol.pdf" file (page 4), it looks like you need to send:
 **,imei:<your imei>,109
and the device will respond with 509 (or 109)
See page 12 for an example of the server/device conversation.

**Comment by deccosantos** [comment]
I have already done this and nothing happens

**Comment by brentfraser** [comment]
Sounds like you need to do some classic trouble shooting on the device.  You need to explore questions like: Do other commands send to the device work?  Does the "Cut off the Oil and Power" command work when you send it via SMS?  I don't think there's much Nick and I can do at this end.

**Comment by nickfox** [comment]
What IS working? Have you tried using the client?

https://github.com/nickfox/GpsTracker/blob/master/servers/tk103/socket-client.php

**Comment by brentfraser** [comment]
A few years ago when we were experimenting with my GPS306A we were able to get the positions from it using the tk103-server.php script.   I've used it to track my vehicle, but I don't recall testing the "help me"/cancel alarm (",E") logic though.

I have not used the socket-client.php.  I assume Nick wrote that for testing the socket code on the server.

**Comment by brentfraser** [comment]
Oops, sorry Nick I thought that was from deccosantos.

**Comment by deccosantos** [comment]
Nickfox thanks for reply, and is i have used the client and it's working greatly with the client you created and with my tracker, I'm getting all data information, i just needed to do a little change in server because my tracker is send info with 13 commas and not with 19 as your server case, but i think it's because my 19 commas answer is disabled.

Brentfraser, Yes, I can send power off by SMS using stop123456 code, it works normally. None of codes is readed by tracker, i have already tried all and didn't work.

But when i used **,imei:<myimei>,E; this works to stop alert "help me" and "door alarm".
I tried set **,imei:<myimei>,J; (this is from another tracker to power off car) but didn't work either, so I think there is another letter code to cut the power of car, and I think, maybe someone knows this letters that works with tk303g

**Comment by nickfox** [comment]
This really is all about being a detective. You need to go and find manuals for different devices until you find the one that matches yours or comes close...

**Comment by deccosantos** [comment]
Hi, I'm back. I tried to send stop command using the coban tracker site http://gpstrackerxy.com and it's work, do you all know what code they send with this site?

**Comment by nickfox** [comment]
well, you can try to use the echo command and see if you can print out a response. I'm not 100% sure that will work. You might try using a packet sniffer like fiddler, wireshark or tcpdump. That might work:

https://en.wikipedia.org/wiki/Packet_analyzer

n

**Comment by deccosantos** [comment]
Nick, maybe you're not understanding me. The response is sent. I have a tcp app into my iphone to connect to the server and response comes. I think the problem is with the code, that is not being accepted by tracker.

**Comment by nickfox** [comment]
I assumed that you wanted to see what was being sent to and returned from the http://gpstrackerxy.com website.

Isn't that what you asked for?

Using a sniffer will answer that question. Let me know if I'm not understanding what you're saying.

**Comment by deccosantos** [comment]
Yes, it's this that i want, but what is sniffer? Where can i find it?

**Comment by nickfox** [comment]
scroll up. :o)

n

**Comment by nickfox** [comment]
I just want to make sure you know what to do. You need to put your phone/device onto your local wifi network and then from a computer you can run fiddle or tcpdump or wireshark and view the traffic from your phone to the http://gpstrackerxy.com website.

That will let you see the codes you need.

**Comment by deccosantos** [comment]
Man, you gave me a great idea. And now i know the letter codes. I connected to gpstrackerxy.com using my tcp app. And i used the terminal from the website to send the code, and it works.

To stop the car the letter is J
To resume is K
To arm the car is L
To disarm is M
To set interval by distance is F,value with 4 digits and m for example F,0300m
To interval by time C,value with 2 digits and s/m/h for example C,30s/C,30m/C,02h

And I realize that the terminal only sends codes to tracker after get a first valid position, with tracker doesn't send a valid position, codes can't be send to tracker, don't know why, but is it.

Since now thanks for all help, and this works for me in Coban tk303g

**Comment by nickfox** [comment]
perfect. good job.

n

**Comment by deccosantos** [comment]
Nick, let me know just one more thing, from your socket server, when response is sent, the message is sent to all clients connected or just for that where data is stored in database?

For example this part of code:

            //send the message back to client
            if (sizeof($response) > 0) {
                fwrite($socket, $response);
            }

This response is just for 1 client or to all connected?

**Comment by nickfox** [comment]
In the server, there is a foreach loop which loops through a collection of sockets. Each socket is connected to one client. The fwrite there is just writing data to a single client socket.

n
